- name: create private key and csr
  shell: openssl req -new -newkey rsa:2048 -sha256 -nodes -outform PEM -keyform PEM -out {{ dir_resources }}/www.{{ domain_name }}.csr -keyout {{ dir_resources }}/www.{{ domain_name }}.key  -subj "/C=JP/ST=Tokyo/O={{ domain_name }}/CN=www.{{ domain_name }}"

- name: create certificate
  shell: openssl x509 -req -days 30 -signkey {{ dir_resources }}/www.{{ domain_name }}.key < {{ dir_resources }}/www.{{ domain_name }}.csr > {{ dir_resources }}/www.{{ domain_name }}.crt

- name: create secret
  shell: kubectl create secret tls www.{{ domain_name }} --cert={{ dir_resources }}/www.{{ domain_name }}.crt --key={{ dir_resources }}/www.{{ domain_name }}.key
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: copy deploy file
  template: src=www.yaml.j2 dest={{ dir_resources }}/www.{{ domain_name }}.yaml

- name: deployment service ingress
  shell: kubectl apply -f {{ dir_resources }}/www.{{ domain_name }}.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

